/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package colecao;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class AddIndFrame extends javax.swing.JInternalFrame {

    /** Creates new form AddIndFrame */
    public AddIndFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addEspTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addGenTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addFamTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btCleatTax = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addUFTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addMunTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addLocTextField = new javax.swing.JTextField();
        btClearLoc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addNomeTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addTelTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        addEmailTextField = new javax.swing.JTextField();
        btClearCol = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        addDataTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addRecTextField = new javax.swing.JTextField();
        addObsTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btClearObs = new javax.swing.JButton();
        btAddInd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabInd = new javax.swing.JTable();
        btDelet = new javax.swing.JButton();
        btShowInd = new javax.swing.JButton();
        btBackInd1 = new javax.swing.JButton();
        btSelect = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tombar Indivíduo"));

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel5.setText("NÚMERO TOMBO:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Taxonômicos"));

        jLabel4.setText("Nome da Espécie");

        jLabel3.setText("Nome do Gênero");

        addFamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFamTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome da Família:");

        btCleatTax.setText("Limpar");
        btCleatTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleatTaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addEspTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(addGenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(addFamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btCleatTax, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addGenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addEspTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCleatTax)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Localidade"));

        addUFTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUFTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Unidade Federativa (UF):");

        jLabel7.setText("Município");

        jLabel8.setText("Localidade");

        btClearLoc.setText("Limpar");
        btClearLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btClearLoc)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(addMunTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(addUFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addUFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMunTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btClearLoc)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Coletor"));

        jLabel9.setText("Nome:");

        addNomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNomeTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Telefone:");

        jLabel17.setText("E-mail:");

        btClearCol.setText("Limpar");
        btClearCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearColActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btClearCol)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(addTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel9)
                        .addComponent(addNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btClearCol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Outras Informações"));

        addDataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Data de Coleta");

        jLabel12.setText("Recipiente");

        addRecTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecTextFieldActionPerformed(evt);
            }
        });

        addObsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObsTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Observações");

        btClearObs.setText("Limpar");
        btClearObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearObsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(addDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(addRecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addObsTextField)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btClearObs)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addObsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btClearObs)
                .addContainerGap())
        );

        btAddInd.setText("Add");
        btAddInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddIndActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btUpdate.setText("Atualizar");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAddInd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(431, 431, 431))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(335, 335, 335))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAddInd)
                            .addComponent(btUpdate))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Indivíduos Tombados"));

        tabInd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TOMBO", "Família", "Gênero", "Espécie", "UF", "Município", "Localidade", "Coletor", "Telefone", "Email", "Data de Coleta", "Recipiente", "Observações"
            }
        ));
        jScrollPane1.setViewportView(tabInd);

        btDelet.setText("Deletar Indivíduo");
        btDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletActionPerformed(evt);
            }
        });

        btShowInd.setText("Ver Indivíduos Tombados");
        btShowInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowIndActionPerformed(evt);
            }
        });

        btBackInd1.setText("Sair");
        btBackInd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackInd1ActionPerformed(evt);
            }
        });

        btSelect.setText("Selecionar");
        btSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btDelet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSelect))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                        .addComponent(btShowInd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btBackInd1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1646, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btShowInd)
                    .addComponent(btDelet)
                    .addComponent(btSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBackInd1)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(461, 461, 461)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddIndActionPerformed
        //String tombo = addTOMBOTextField1.getText();
        String nome = addNomeTextField.getText();
        String telefone = addTelTextField.getText();
        String email = addEmailTextField.getText();
        String familia = addFamTextField.getText();
        String genero = addGenTextField.getText();
        String especie1 = addEspTextField.getText();
        String data = addDataTextField.getText();
        String obs = addObsTextField.getText();
        String recipiente = addRecTextField.getText();
        String localidade1 = addLocTextField.getText();
        String municipio = addMunTextField.getText();
        String uf = addUFTextField.getText();

        Especie especie = EspecieFactory.getInstance().findEsp(familia,genero,especie1);
        Coletor coletor = ColetorFactory.getInstance().findCol(nome,telefone,email);
        Localidade localidade = LocalidadeFactory.getInstance().findLoc(uf,municipio,localidade1);

        Individuo i = IndividuoFactory.getInstance().cadastrarIndividuo(especie, coletor, localidade, data, recipiente, obs);

        //addTOMBOTextField1.setText("");
        addNomeTextField.setText("");
        addTelTextField.setText("");
        addEmailTextField.setText("");
        addFamTextField.setText("");
        addGenTextField.setText("");
        addEspTextField.setText("");
        addDataTextField.setText("");
        addObsTextField.setText("");
        addRecTextField.setText("");
        addLocTextField.setText("");
        addMunTextField.setText("");
        addUFTextField.setText("");
        jLabel1.setText(String.valueOf(Individuo.getT()));
        
        initIndTable();
                        
    }//GEN-LAST:event_btAddIndActionPerformed

    private void btClearObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearObsActionPerformed
        addDataTextField.setText("");
        addObsTextField.setText("");
        addRecTextField.setText("");
    }//GEN-LAST:event_btClearObsActionPerformed

    private void addObsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addObsTextFieldActionPerformed

    private void addRecTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRecTextFieldActionPerformed

    private void addDataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDataTextFieldActionPerformed

    private void btClearColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearColActionPerformed
        addNomeTextField.setText("");
        addTelTextField.setText("");
        addEmailTextField.setText("");
    }//GEN-LAST:event_btClearColActionPerformed

    private void addNomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNomeTextFieldActionPerformed

    private void btClearLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearLocActionPerformed
        addLocTextField.setText("");
        addMunTextField.setText("");
        addUFTextField.setText("");
    }//GEN-LAST:event_btClearLocActionPerformed

    private void addUFTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUFTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUFTextFieldActionPerformed

    private void btCleatTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleatTaxActionPerformed
        addFamTextField.setText("");
        addGenTextField.setText("");
        addEspTextField.setText("");
    }//GEN-LAST:event_btCleatTaxActionPerformed

    private void addFamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFamTextFieldActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        jLabel1.setText(String.valueOf(Individuo.getT()));
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void btDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletActionPerformed
        int row = tabInd.getSelectedRow();
        int column = 0;

        Object t = tabInd.getValueAt(row, column);

        int tombo = Integer.valueOf(t.toString());

        Individuo iRemove = IndividuoFactory.getInstance().findInd(tombo);

        IndividuoFactory.getInstance().deleteInd(iRemove, iRemove.getLocalidade(), iRemove.getColetor(), iRemove.getEspecie());
        initIndTable();
    }//GEN-LAST:event_btDeletActionPerformed

    private void btShowIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowIndActionPerformed
        initIndTable();
    }//GEN-LAST:event_btShowIndActionPerformed

    private void btBackInd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackInd1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btBackInd1ActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        int row = tabInd.getSelectedRow(); 
        Object t = tabInd.getValueAt(row, 0);
        Object f = tabInd.getValueAt(row, 1);
        Object g = tabInd.getValueAt(row, 2);
        Object e = tabInd.getValueAt(row, 3);
        Object u = tabInd.getValueAt(row, 4);
        Object m = tabInd.getValueAt(row, 5);        
        Object l = tabInd.getValueAt(row, 6);
        Object c = tabInd.getValueAt(row, 7);
        Object d = tabInd.getValueAt(row, 8);
        Object r = tabInd.getValueAt(row, 9);        
        Object o = tabInd.getValueAt(row, 10);
        
        int tombo = Integer.valueOf(t.toString());
                
        Individuo i1 = IndividuoFactory.getInstance().findInd(tombo);

        String dt = addDataTextField.getText();
        String email = addEmailTextField.getText();
        String esp = addEspTextField.getText();
        String fam = addFamTextField.getText();
        String gen = addGenTextField.getText();
        String loc = addLocTextField.getText();
        String mun = addMunTextField.getText();
        String col = addNomeTextField.getText();
        String obs = addObsTextField.getText();
        String rec = addRecTextField.getText();
        String tel = addTelTextField.getText();
        String uf = addUFTextField.getText();        
        
        IndividuoFactory.getInstance().updateInd(i1, fam, gen, esp, uf, mun, loc, col, tel, email, dt, rec, obs);
        initIndTable();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectActionPerformed
        int row = tabInd.getSelectedRow(); 
        Object f = tabInd.getValueAt(row, 1);
        Object g = tabInd.getValueAt(row, 2);
        Object e = tabInd.getValueAt(row, 3);
        Object u = tabInd.getValueAt(row, 4);
        Object m = tabInd.getValueAt(row, 5);        
        Object l = tabInd.getValueAt(row, 6);
        Object c = tabInd.getValueAt(row, 7);
        Object t = tabInd.getValueAt(row,8);
        Object em = tabInd.getValueAt(row, 9);
        Object d = tabInd.getValueAt(row, 10);
        Object r = tabInd.getValueAt(row, 11); 
        Object o = tabInd.getValueAt(row, 12);
        
        String fam = f.toString();
        String gen = g.toString();
        String esp = e.toString();
        String uf = u.toString();
        String mun = m.toString();
        String loc = l.toString();
        String col = c.toString();
        String dt = d.toString();
        String rec = r.toString();
        String obs = o.toString();
        String tel = t.toString();
        String email = em.toString();
        
        addDataTextField.setText(dt);
        addEmailTextField.setText(email);
        addEspTextField.setText(esp);
        addFamTextField.setText(fam);
        addGenTextField.setText(gen);
        addLocTextField.setText(loc);
        addMunTextField.setText(mun);
        addNomeTextField.setText(col);
        addObsTextField.setText(obs);
        addRecTextField.setText(rec);
        addTelTextField.setText(tel);
        addUFTextField.setText(uf);  
        
        
    }//GEN-LAST:event_btSelectActionPerformed

    private void initIndTable(){
        DefaultTableModel m = (DefaultTableModel) tabInd.getModel();
        m.setRowCount(0);
        for(Individuo i : IndividuoFactory.getInstance().findAll()){
            m.addRow(new Object[] {i.getTombo(), i.getEspecie().getGenero().getFamilia(), i.getEspecie().getGenero().getNome(), i.getEspecie().getNome(), i.getLocalidade().getUf(), i.getLocalidade().getMunicipio(), i.getLocalidade().getLocalidade(), i.getColetor().getNome(), i.getColetor().getTelefone(), i.getColetor().getEmail(), i.getData(), i.getRecipiente(), i.getObs()});
        }
       } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addDataTextField;
    private javax.swing.JTextField addEmailTextField;
    private javax.swing.JTextField addEspTextField;
    private javax.swing.JTextField addFamTextField;
    private javax.swing.JTextField addGenTextField;
    private javax.swing.JTextField addLocTextField;
    private javax.swing.JTextField addMunTextField;
    private javax.swing.JTextField addNomeTextField;
    private javax.swing.JTextField addObsTextField;
    private javax.swing.JTextField addRecTextField;
    private javax.swing.JTextField addTelTextField;
    private javax.swing.JTextField addUFTextField;
    private javax.swing.JButton btAddInd;
    private javax.swing.JButton btBackInd1;
    private javax.swing.JButton btClearCol;
    private javax.swing.JButton btClearLoc;
    private javax.swing.JButton btClearObs;
    private javax.swing.JButton btCleatTax;
    private javax.swing.JButton btDelet;
    private javax.swing.JButton btSelect;
    private javax.swing.JButton btShowInd;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabInd;
    // End of variables declaration//GEN-END:variables

    //IndividuoFactory.getInstance().cadastrarIndividuo(especie, tombo, coletor, localidade, data, recipiente, obs)
      
   
}
