/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colecao;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class AddLocFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddLocFrame
     */
    public AddLocFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addUFTextField = new javax.swing.JTextField();
        btClearLoc = new javax.swing.JButton();
        btAddLoc = new javax.swing.JButton();
        addMunTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addLocTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabLoc = new javax.swing.JTable();
        btShowLoc = new javax.swing.JButton();
        btBackLoc = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSelect = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Localidade"));

        jLabel2.setText("Unidade Federativa (UF):");

        addUFTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUFTextFieldActionPerformed(evt);
            }
        });

        btClearLoc.setText("Limpar");
        btClearLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearLocActionPerformed(evt);
            }
        });

        btAddLoc.setText("Add");
        btAddLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLocActionPerformed(evt);
            }
        });

        jLabel3.setText("Município");

        jLabel4.setText("Localidade");

        btUpdate.setText("Atualizar");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAddLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(addMunTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(addUFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btClearLoc))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addUFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMunTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btClearLoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddLoc)
                    .addComponent(btUpdate)))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localidades Cadastradas"));

        tabLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UF", "Município", "Localidade"
            }
        ));
        jScrollPane1.setViewportView(tabLoc);

        btShowLoc.setText("Ver Localidades Cadastradas");
        btShowLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowLocActionPerformed(evt);
            }
        });

        btBackLoc.setText("Sair");
        btBackLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackLocActionPerformed(evt);
            }
        });

        btDelete.setText("Deletar");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btSelect.setText("Selecionar");
        btSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 356, Short.MAX_VALUE)
                        .addComponent(btBackLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSelect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btShowLoc)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btShowLoc)
                            .addComponent(btDelete)
                            .addComponent(btSelect)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBackLoc)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUFTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUFTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUFTextFieldActionPerformed

    private void btClearLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearLocActionPerformed
        addUFTextField.setText("");
        addMunTextField.setText("");
        addLocTextField.setText("");
    }//GEN-LAST:event_btClearLocActionPerformed

    private void btAddLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLocActionPerformed
        String UF = addUFTextField.getText();
        String municipio = addMunTextField.getText();
        String localidade = addLocTextField.getText();

        Localidade l = LocalidadeFactory.getInstance().cadastrarLocalidade(UF, municipio, localidade);

        initLocTable();
        addUFTextField.setText("");
        addMunTextField.setText("");
        addLocTextField.setText("");
    }//GEN-LAST:event_btAddLocActionPerformed

    private void initLocTable(){
        DefaultTableModel m = (DefaultTableModel) tabLoc.getModel();
        m.setRowCount(0);
        for(Localidade l : LocalidadeFactory.getInstance().findAll()){
            m.addRow(new Object[] {l.getUf(), l.getMunicipio(), l.getLocalidade()});
        }
    }       
    
    private void btShowLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowLocActionPerformed
        initLocTable();
    }//GEN-LAST:event_btShowLocActionPerformed

    private void btBackLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackLocActionPerformed
        this.dispose();
    }//GEN-LAST:event_btBackLocActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
       int row = tabLoc.getSelectedRow();
       int columnFam = 0;
       int columnGen = 1; 
       int columnEsp = 2;
       
       Object u = tabLoc.getValueAt(row, columnFam);
       Object m = tabLoc.getValueAt(row, columnGen);
       Object l = tabLoc.getValueAt(row, columnEsp);

       String uf = u.toString();       
       String municipio = m.toString();       
       String localidade = l.toString(); 
       
       Localidade lRemove = LocalidadeFactory.getInstance().findLoc(uf, municipio, localidade);
       
       if((LocalidadeFactory.getInstance().deleteLoc(lRemove))==true){
            initLocTable();
       }
       
       else{
           ImpossivelDeletar frame = new ImpossivelDeletar();
           frame.setVisible(true);
       }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
       int row = tabLoc.getSelectedRow();
       int columnFam = 0;
       int columnGen = 1; 
       int columnEsp = 2;
       
       Object u = tabLoc.getValueAt(row, columnFam);
       Object m = tabLoc.getValueAt(row, columnGen);
       Object l = tabLoc.getValueAt(row, columnEsp);

       String uf = u.toString();       
       String municipio = m.toString();       
       String localidade = l.toString(); 

       Localidade l1 = LocalidadeFactory.getInstance().findLoc(uf,municipio,localidade);

       String ufNovo = addUFTextField.getText();
       String munNovo = addMunTextField.getText();
       String LocNovo = addLocTextField.getText();

       LocalidadeFactory.getInstance().updateLoc(l1, ufNovo, munNovo, LocNovo);
       initLocTable();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectActionPerformed
        int row = tabLoc.getSelectedRow();
        int columnFam = 0;
        int columnGen = 1; 
        int columnEsp = 2;

        Object u = tabLoc.getValueAt(row, columnFam);
        Object m = tabLoc.getValueAt(row, columnGen);
        Object l = tabLoc.getValueAt(row, columnEsp);

        String uf = u.toString();       
        String municipio = m.toString();       
        String localidade = l.toString(); 
       
        addUFTextField.setText(uf);
        addMunTextField.setText(municipio);
        addLocTextField.setText(localidade);       
    }//GEN-LAST:event_btSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addLocTextField;
    private javax.swing.JTextField addMunTextField;
    private javax.swing.JTextField addUFTextField;
    private javax.swing.JButton btAddLoc;
    private javax.swing.JButton btBackLoc;
    private javax.swing.JButton btClearLoc;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSelect;
    private javax.swing.JButton btShowLoc;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabLoc;
    // End of variables declaration//GEN-END:variables
}
