/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colecao;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class AddFamFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddFamFrame
     */
    public AddFamFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addFamTextField = new javax.swing.JTextField();
        btClearFam = new javax.swing.JButton();
        btAddFam = new javax.swing.JButton();
        btAtualizarFam = new javax.swing.JButton();
        btBackFam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFam = new javax.swing.JTable();
        btShowFam = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSelectFam = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Família"));

        jLabel2.setText("Nome da Família:");

        btClearFam.setText("Limpar");
        btClearFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearFamActionPerformed(evt);
            }
        });

        btAddFam.setText("Add");
        btAddFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFamActionPerformed(evt);
            }
        });

        btAtualizarFam.setText("Atualizar");
        btAtualizarFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarFamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btClearFam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAddFam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addFamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualizarFam, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel2)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addFamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClearFam)
                    .addComponent(btAddFam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizarFam)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        btBackFam.setText("Sair");
        btBackFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackFamActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Famílias Cadastradas"));

        tabFam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ));
        jScrollPane1.setViewportView(tabFam);

        btShowFam.setText("Ver Famílias Cadastradas");
        btShowFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowFamActionPerformed(evt);
            }
        });

        btDelete.setText("Deletar");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btSelectFam.setText("Selecionar");
        btSelectFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectFamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 495, Short.MAX_VALUE)
                        .addComponent(btBackFam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSelectFam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btShowFam))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btShowFam)
                    .addComponent(btDelete)
                    .addComponent(btSelectFam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBackFam)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackFamActionPerformed
        this.dispose();
    }//GEN-LAST:event_btBackFamActionPerformed

    private void btAddFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFamActionPerformed
       String nome = addFamTextField.getText();
              
       Familia f = FamiliaFactory.getInstance().cadastrarFamilia(nome);
       initFamTable();
       addFamTextField.setText("");       
    }//GEN-LAST:event_btAddFamActionPerformed

    private void btClearFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearFamActionPerformed
        addFamTextField.setText("");
    }//GEN-LAST:event_btClearFamActionPerformed

    private void btShowFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowFamActionPerformed
        initFamTable();
    }//GEN-LAST:event_btShowFamActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
       int row = tabFam.getSelectedRow();
       int column = 0;
        
       Object f = tabFam.getValueAt(row, column);
       
       String familia = f.toString();
       Familia fRemove = FamiliaFactory.getInstance().findFam(familia);
       
       if((FamiliaFactory.getInstance().deleteFam(fRemove))==true){
            initFamTable();
       }
       
       else{
           ImpossivelDeletar frame = new ImpossivelDeletar();
           frame.setVisible(true);
       }
         
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btSelectFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectFamActionPerformed
        int row = tabFam.getSelectedRow();
        int column = 0;
        Object f = tabFam.getValueAt(row,column);
        
        String familia = f.toString();
        addFamTextField.setText(familia);             
        
    }//GEN-LAST:event_btSelectFamActionPerformed

    private void btAtualizarFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarFamActionPerformed
        int row = tabFam.getSelectedRow();
        int column = 0;
        Object f = tabFam.getValueAt(row,column);
        String familia = f.toString();
        Familia f1 = FamiliaFactory.getInstance().findFam(familia);
        
        String nomeNovo = addFamTextField.getText();   
        FamiliaFactory.getInstance().updateFam(f1, nomeNovo);
        initFamTable();
    }//GEN-LAST:event_btAtualizarFamActionPerformed

    private void initFamTable(){
        DefaultTableModel m = (DefaultTableModel) tabFam.getModel();
        m.setRowCount(0);
        for(Familia f : FamiliaFactory.getInstance().findAll()){
            m.addRow(new Object[] {f.getNome()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addFamTextField;
    private javax.swing.JButton btAddFam;
    private javax.swing.JButton btAtualizarFam;
    private javax.swing.JButton btBackFam;
    private javax.swing.JButton btClearFam;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSelectFam;
    private javax.swing.JButton btShowFam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabFam;
    // End of variables declaration//GEN-END:variables

     


}
