/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colecao;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class VerIndFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerIndFrame
     */
    public VerIndFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabInd = new javax.swing.JTable();
        btShowInd = new javax.swing.JButton();
        btBackInd = new javax.swing.JButton();
        btDelet = new javax.swing.JButton();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Indivíduos Tombados"));

        tabInd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO TOMBO", "Família", "Gênero", "Espécie", "UF", "Município", "Localidade", "Coletor", "Data de Coleta", "Recipiente"
            }
        ));
        jScrollPane1.setViewportView(tabInd);

        btShowInd.setText("Ver Indivíduos Tombados");
        btShowInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowIndActionPerformed(evt);
            }
        });

        btBackInd.setText("Sair");
        btBackInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackIndActionPerformed(evt);
            }
        });

        btDelet.setText("Deletar Indivíduo");
        btDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(778, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btBackInd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDelet)
                        .addGap(69, 69, 69)
                        .addComponent(btShowInd)))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btShowInd)
                    .addComponent(btDelet))
                .addGap(4, 4, 4)
                .addComponent(btBackInd)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addGap(81, 81, 81)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btShowIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowIndActionPerformed
        initIndTable();
    }//GEN-LAST:event_btShowIndActionPerformed

    private void btBackIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackIndActionPerformed
        this.dispose();
    }//GEN-LAST:event_btBackIndActionPerformed

    private void btDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletActionPerformed
       int row = tabInd.getSelectedRow();
       int column = 0;
        
       Object t = tabInd.getValueAt(row, column);
       
       String tombo = t.toString();
       Individuo iRemove = IndividuoFactory.getInstance().findInd(tombo);
                
       IndividuoFactory.getInstance().deleteInd(iRemove, iRemove.getLocalidade(), iRemove.getColetor(), iRemove.getEspecie());
       initIndTable();        
    }//GEN-LAST:event_btDeletActionPerformed

    private void initIndTable(){
        DefaultTableModel m = (DefaultTableModel) tabInd.getModel();
        m.setRowCount(0);
        for(Individuo i : IndividuoFactory.getInstance().findAll()){
            m.addRow(new Object[] {i.getTombo(), i.getEspecie().getGenero().getFamilia(), i.getEspecie().getGenero().getNome(), i.getEspecie().getNome(), i.getLocalidade().getUf(), i.getLocalidade().getMunicipio(), i.getLocalidade().getLocalidade(), i.getColetor().getNome(), i.getData(), i.getRecipiente(), i.getObs()});
        }
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackInd;
    private javax.swing.JButton btDelet;
    private javax.swing.JButton btShowInd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabInd;
    // End of variables declaration//GEN-END:variables
}
